import "~/styles/globals.css";

import { Inter } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { ClerkProvider, UserButton } from "@clerk/nextjs";
import { Nav } from "./_nav";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="de">
        <body className={`font-sans ${inter.variable} h-screen`}>
          <TRPCReactProvider>
            <div className="flex w-full justify-end p-2">
              <UserButton />
            </div>
            {children}
            <Nav className=" absolute bottom-0" />
          </TRPCReactProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
